// `bun run build:web`: bundles the notebook's script and CodeMirror into
// web/notebook.js, which is committed, so an install or a checkout serves it with no
// install step and no network. The first line is a hash of what it was built from;
// cli/notes.test.ts fails when the committed file no longer matches.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

const root = dirname(import.meta.dir);
const SOURCES = ["web/notebook.ts", "web/notes-lib.ts"];
export const OUT = join(root, "web", "notebook.js");

// The sources and the exact dependency versions: a CodeMirror bump is a rebuild too.
export function sourceHash() {
  const h = createHash("sha256");
  for (const f of SOURCES) h.update(readFileSync(join(root, f), "utf8").replace(/\r\n/g, "\n"));
  h.update(JSON.stringify(JSON.parse(readFileSync(join(root, "package.json"), "utf8")).devDependencies ?? {}));
  return h.digest("hex").slice(0, 16);
}
export const banner = () => `/* kaizen notebook ${sourceHash()} -- generated by bun run build:web from web/notebook.ts; do not edit */`;

if (import.meta.main) {
  const r = await Bun.build({ entrypoints: [join(root, "web", "notebook.ts")], target: "browser", minify: true });
  if (!r.success) { for (const l of r.logs) console.error(l); process.exit(1); }
  writeFileSync(OUT, banner() + "\n" + await r.outputs[0]!.text());
  console.log(`  web/notebook.js  ${(Bun.file(OUT).size / 1024).toFixed(0)} KB`);
}
